/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ActivityItem {
  'activityType' : ActivityType,
  'studentId' : string,
  'studentName' : string,
  'value' : string,
  'date' : string,
}
export type ActivityType = { 'Mood' : null } |
  { 'Behavior' : null };
export type AppRole = { 'Teacher' : null } |
  { 'Student' : string } |
  { 'Admin' : null };
export interface BehaviorEntry {
  'behavior' : BehaviorType,
  'studentId' : string,
  'date' : string,
  'entryId' : bigint,
}
export type BehaviorType = { 'LowParticipation' : null } |
  { 'Aggressive' : null } |
  { 'Active' : null } |
  { 'Silent' : null };
export interface MoodEntry {
  'studentId' : string,
  'date' : string,
  'entryId' : bigint,
  'moodScore' : bigint,
}
export type RiskLevel = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null };
export interface Student {
  'id' : string,
  'name' : string,
  'section' : string,
  'grade' : string,
}
export interface StudentSummary {
  'id' : string,
  'latestBehavior' : [] | [BehaviorType],
  'name' : string,
  'latestMood' : [] | [bigint],
  'section' : string,
  'grade' : string,
  'riskLevel' : RiskLevel,
}
export interface UserProfile { 'name' : string, 'role' : AppRole }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addStudent' : ActorMethod<[Student], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exportDataAsCSV' : ActorMethod<[], string>,
  'getAllStudentSummaries' : ActorMethod<[], Array<StudentSummary>>,
  'getBehaviorHistory' : ActorMethod<[string], Array<BehaviorEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMoodHistory' : ActorMethod<[string], Array<MoodEntry>>,
  'getRecentActivityFeed' : ActorMethod<[], Array<ActivityItem>>,
  'getStudentsByGrade' : ActorMethod<[string], Array<Student>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listStudents' : ActorMethod<[], Array<Student>>,
  'recordBehaviorEntry' : ActorMethod<[string, string], undefined>,
  'recordMoodEntry' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];