/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Student = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'section' : IDL.Text,
  'grade' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BehaviorType = IDL.Variant({
  'LowParticipation' : IDL.Null,
  'Aggressive' : IDL.Null,
  'Active' : IDL.Null,
  'Silent' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
});
export const StudentSummary = IDL.Record({
  'id' : IDL.Text,
  'latestBehavior' : IDL.Opt(BehaviorType),
  'name' : IDL.Text,
  'latestMood' : IDL.Opt(IDL.Nat),
  'section' : IDL.Text,
  'grade' : IDL.Text,
  'riskLevel' : RiskLevel,
});
export const BehaviorEntry = IDL.Record({
  'behavior' : BehaviorType,
  'studentId' : IDL.Text,
  'date' : IDL.Text,
  'entryId' : IDL.Nat,
});
export const AppRole = IDL.Variant({
  'Teacher' : IDL.Null,
  'Student' : IDL.Text,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppRole });
export const MoodEntry = IDL.Record({
  'studentId' : IDL.Text,
  'date' : IDL.Text,
  'entryId' : IDL.Nat,
  'moodScore' : IDL.Nat,
});
export const ActivityType = IDL.Variant({
  'Mood' : IDL.Null,
  'Behavior' : IDL.Null,
});
export const ActivityItem = IDL.Record({
  'activityType' : ActivityType,
  'studentId' : IDL.Text,
  'studentName' : IDL.Text,
  'value' : IDL.Text,
  'date' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'exportDataAsCSV' : IDL.Func([], [IDL.Text], ['query']),
  'getAllStudentSummaries' : IDL.Func([], [IDL.Vec(StudentSummary)], ['query']),
  'getBehaviorHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BehaviorEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMoodHistory' : IDL.Func([IDL.Text], [IDL.Vec(MoodEntry)], ['query']),
  'getRecentActivityFeed' : IDL.Func([], [IDL.Vec(ActivityItem)], ['query']),
  'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
  'recordBehaviorEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'recordMoodEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Student = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'section' : IDL.Text,
    'grade' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BehaviorType = IDL.Variant({
    'LowParticipation' : IDL.Null,
    'Aggressive' : IDL.Null,
    'Active' : IDL.Null,
    'Silent' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const StudentSummary = IDL.Record({
    'id' : IDL.Text,
    'latestBehavior' : IDL.Opt(BehaviorType),
    'name' : IDL.Text,
    'latestMood' : IDL.Opt(IDL.Nat),
    'section' : IDL.Text,
    'grade' : IDL.Text,
    'riskLevel' : RiskLevel,
  });
  const BehaviorEntry = IDL.Record({
    'behavior' : BehaviorType,
    'studentId' : IDL.Text,
    'date' : IDL.Text,
    'entryId' : IDL.Nat,
  });
  const AppRole = IDL.Variant({
    'Teacher' : IDL.Null,
    'Student' : IDL.Text,
    'Admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : AppRole });
  const MoodEntry = IDL.Record({
    'studentId' : IDL.Text,
    'date' : IDL.Text,
    'entryId' : IDL.Nat,
    'moodScore' : IDL.Nat,
  });
  const ActivityType = IDL.Variant({
    'Mood' : IDL.Null,
    'Behavior' : IDL.Null,
  });
  const ActivityItem = IDL.Record({
    'activityType' : ActivityType,
    'studentId' : IDL.Text,
    'studentName' : IDL.Text,
    'value' : IDL.Text,
    'date' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'exportDataAsCSV' : IDL.Func([], [IDL.Text], ['query']),
    'getAllStudentSummaries' : IDL.Func(
        [],
        [IDL.Vec(StudentSummary)],
        ['query'],
      ),
    'getBehaviorHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BehaviorEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMoodHistory' : IDL.Func([IDL.Text], [IDL.Vec(MoodEntry)], ['query']),
    'getRecentActivityFeed' : IDL.Func([], [IDL.Vec(ActivityItem)], ['query']),
    'getStudentsByGrade' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listStudents' : IDL.Func([], [IDL.Vec(Student)], ['query']),
    'recordBehaviorEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'recordMoodEntry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };